creharmony/node-etsy-client

env/initEnv.example.sh
src/EtsyClient.js

Fix #4 add ETSY_LANG

---

.travis.yml
Example.js
src/EtsyClient.d.ts
src/EtsyClient.js

- Fix #8 get shop sections and use etsy method names
- Fix #7 fix travis deploy

Fix #8 get shop sections, Fix #7 travis publish

---

.gitignore
Example.js
src/EtsyClient.d.ts
src/EtsyClient.js

Fix #11 getInventory getProduct

Fix #11 getInventory getProduct

---

README.md

Fix #15 add GREN

---

.github/workflows/main.yml
README.md
package.json
src/EtsyClient.js
tests/unauthenticated_client.test.js

Fix #19 add rate limiter - github action npm audit

Fix #19 add rate limiter - github action npm audit

---

README.md
package.json
src/EtsyClient.js
tests/unauthenticated_client.test.js
tests/unauthenticated_rate.test.js

Fix #19 again with [susi-rali](https://github.com/creharmony/susi-rali)

Fix #19 again with susi-rali

---

package.json

Fix #19 update susi-rali to 0.0.2
- npm update too

Fix #19 update susi-rali to 0.0.2

---

.github/workflows/audit.yml
README.md

Fix #21 npm audit

---

package.json

Fix #25  remove node engine restriction

Fix #25  remove node engine restriction

---

.github/workflows/audit.yml
.github/workflows/main.yml
.github/workflows/minor.yml
.github/workflows/patch.yml

Fix #28 node setup with cache

---

.github/workflows/audit.yml
.github/workflows/main.yml
.github/workflows/minor.yml
.github/workflows/patch.yml
package-lock.json
package.json

Fix #30 npm audit
- move dev deps to dev deps
- upd versions

Fix #30 npm audit

---

package-lock.json
package.json
src/EtsyClient.js
tests/authenticated_client.test.js
tests/unauthenticated_client.test.js
tests/unauthenticated_rate.test.js

Fix #32 node-fetch 3.2 and ESM compatible

Fix #32 node-fetch 3.2 and ESM compatible

---

src/EtsyClient.js
tests/unauthenticated_client.test.js

Fix #34 use query language option if any

Fix #34 use query language option if any

---

README.md
lib/export.js
package.json

for version `1.0.0-beta.1`
way to use beta: 
```
import { OAuth2Service }  from 'node-etsy-client';
or
import { EtsyClientV3 } from 'node-etsy-client';
```

Fix #43 fix export

---

.github/workflows/BETA_README.md
src/EtsyClientV3.js
tests/v3/authenticated_client.test.js
tests/v3/manual_oauth_client.tst.js
tests/v3/unauthenticated_client.test.js

Fix #46 - add setAT,getNbCall,override lang, and upd etsy/open-api#420

Fix #46 - add setAT,getNbCall,override lang, and upd etsy/open-api#420

---

README.md
client-sample/typescript-client/.gitignore
client-sample/typescript-client/linkLib.sh
client-sample/typescript-client/out/index.js
client-sample/typescript-client/package-lock.json
client-sample/typescript-client/package.json
client-sample/typescript-client/src/index.ts
client-sample/typescript-client/tsconfig.json
lib/export.d.ts
lib/export.js
package.json
src/OAuth2Service.d.ts
tests/v3/manual_oauth_client.tst.js

Issue #45 fix typescript export, remove beta label
improve manual test

Issue #45 fix typescript export, remove beta label

---

.github/workflows/main.yml
package-lock.json
package.json
src/EtsyClientV2.js
src/EtsyClientV3.js
src/OAuth2Service.js
tests/v2/authenticated_client.test.js
tests/v2/unauthenticated_client.test.js
tests/v3/authenticated_client.test.js
tests/v3/manual_oauth_client.tst.js
tests/v3/unauthenticated_client.test.js

Fix #51 replace node-fetch by axios

Fix #51 replace node-fetch by axios

---

client-sample/typescript-client/package-lock.json
client-sample/typescript-client/package.json
package-lock.json
package.json

Fix #53 clean node-fetch and update deps

Fix #53 clean node-fetch and update deps

---

package-lock.json
package.json

Fix #56 npm audit and minimatch

Fix #56 npm audit and minimatch

---

.github/workflows/major.yml
.github/workflows/minor.yml

Fix #59 add major workflow

---

.github/CONTRIBUTING.md
README.md

Fix #69 use gh create release and improve how to contribute doc

Fix #69 use gh create release and improve how to contribute doc
